### ISSUE TITLE
How do I connect to a pre-existing signaling/relay server?

### ISSUE THREAD

**Issue by rei-gun** [noctisatrae/gunpoint#8]
I don't see where I can set the IP & port of a pre-existing signaling server.

Referring to this line from the tutorial where you connect to other peers:

` var gun = Gun(['http://localhost:8765/gun', 'https://mvp-gun.herokuapp.com/gun', 'https://e2eec.herokuapp.com/gun']);`

**Comment by noctisatrae** [comment]
Hi ! Thanks for reaching out 😄. It’s a feature coming : I’m going to make the `config.json` more useful. You’ll be able to configure Gun as you want. 

Answer : this feature is coming.

I was going to do it today. Can I close the issue ?

**Comment by noctisatrae** [comment]
We solved this issue on Discord so, I’m going to close it.
